name: Build and deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      run: |
        cd packages/mp_dom_runtime/
        npm install -g browserify uglify-js typescript terser
        npm install
        npm run build
        cd packages/mp_web_features
        npm install
        npm run build
        cd ../../
        cd ../mp_kbone
        npm install
        npm run build
        cd ../mp_dom_runtime
        git config --global user.email "ci@mpflutter.com"
        git config --global user.name "GitHub CI bot"
        git clone https://github.com/mpflutter/dist.git mpflutter_dist
        mkdir -p mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")
        cp -rf dist_web mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")/dist_web
        cp -rf dist_weapp mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")/dist_weapp
        cd mpflutter_dist
        git add .
        git diff-index --quiet HEAD || git commit --message "CI Bot commit"
        git push "https://ponycui:${{ secrets.GH_TOKEN }}@github.com/mpflutter/dist.git" --set-upstream "master"
        cd ../../../
        cd deployer
        npm install
        node ./release.js
        node ./release_pod.js
    - name: Upload COS
      uses: mpflutter/cos-action@master
      with:
        secret_id: ${{ secrets.COS_SECRET_ID }}
        secret_key: ${{ secrets.COS_SECRET_KEY }}
        cos_bucket: mpflutter-dist-1253771526
        cos_region: ap-guangzhou
        local_path: packages/mp_dom_runtime/mpflutter_dist/${{ github.ref_name }}
        remote_path: dist/${{ github.ref_name }}
        clean: true